// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// matInGeomC
NumericMatrix matInGeomC(NumericMatrix& mat, NumericMatrix& geom, bool negative);
RcppExport SEXP _geomTools_matInGeomC(SEXP matSEXP, SEXP geomSEXP, SEXP negativeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type geom(geomSEXP);
    Rcpp::traits::input_parameter< bool >::type negative(negativeSEXP);
    rcpp_result_gen = Rcpp::wrap(matInGeomC(mat, geom, negative));
    return rcpp_result_gen;
END_RCPP
}
// getValuesMatC
NumericVector getValuesMatC(NumericMatrix& mat);
RcppExport SEXP _geomTools_getValuesMatC(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(getValuesMatC(mat));
    return rcpp_result_gen;
END_RCPP
}
// subNumNumC
NumericMatrix subNumNumC(NumericMatrix& mat, NumericVector& replace, NumericVector with);
RcppExport SEXP _geomTools_subNumNumC(SEXP matSEXP, SEXP replaceSEXP, SEXP withSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type replace(replaceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type with(withSEXP);
    rcpp_result_gen = Rcpp::wrap(subNumNumC(mat, replace, with));
    return rcpp_result_gen;
END_RCPP
}
// subChrIntC
IntegerMatrix subChrIntC(CharacterMatrix& mat, CharacterVector& replace, IntegerVector& with);
RcppExport SEXP _geomTools_subChrIntC(SEXP matSEXP, SEXP replaceSEXP, SEXP withSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< CharacterVector& >::type replace(replaceSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type with(withSEXP);
    rcpp_result_gen = Rcpp::wrap(subChrIntC(mat, replace, with));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_geomTools_matInGeomC", (DL_FUNC) &_geomTools_matInGeomC, 3},
    {"_geomTools_getValuesMatC", (DL_FUNC) &_geomTools_getValuesMatC, 1},
    {"_geomTools_subNumNumC", (DL_FUNC) &_geomTools_subNumNumC, 3},
    {"_geomTools_subChrIntC", (DL_FUNC) &_geomTools_subChrIntC, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_geomTools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
