# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matInGeomC <- function(mat, geom, negative) {
    .Call('_geomTools_matInGeomC', PACKAGE = 'geomTools', mat, geom, negative)
}

getValuesMatC <- function(mat) {
    .Call('_geomTools_getValuesMatC', PACKAGE = 'geomTools', mat)
}

subNumNumC <- function(mat, replace, with) {
    .Call('_geomTools_subNumNumC', PACKAGE = 'geomTools', mat, replace, with)
}

subChrIntC <- function(mat, replace, with) {
    .Call('_geomTools_subChrIntC', PACKAGE = 'geomTools', mat, replace, with)
}

