# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matInGeomC <- function(mat, geom, negative) {
    .Call('_geometr_matInGeomC', PACKAGE = 'geometr', mat, geom, negative)
}

pointInGeomC <- function(vert, geom, invert) {
    .Call('_geometr_pointInGeomC', PACKAGE = 'geometr', vert, geom, invert)
}

getValuesMatC <- function(mat) {
    .Call('_geometr_getValuesMatC', PACKAGE = 'geometr', mat)
}

subChrIntC <- function(mat, replace, with) {
    .Call('_geometr_subChrIntC', PACKAGE = 'geometr', mat, replace, with)
}

sortUniqueC <- function(x) {
    .Call('_geometr_sortUniqueC', PACKAGE = 'geometr', x)
}

